context:
  name: fmm3dpy
  version: 1.0.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - cd python
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - meson-python
    - numpy >=2.0.0
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
  run:
    - python>=3.9
    - numpy >=1.26.4

tests:
  - python:
      imports:
        - fmm3dpy
